services:
  database-test:
    image: postgres:14-alpine
    container_name: database-test
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: user_test
      POSTGRES_PASSWORD: pass_test
      POSTGRES_DB: transcendence_test
